#!/bin/bash
# This is a simple post deploy hook executed after your application
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.

echo "Copying uploads back into public directory"
cp -r "${OPENSHIFT_DATA_DIR}/backups/uploads" "${OPENSHIFT_REPO_DIR}/public/"
