version: "3.2"
services:
  db:
    image: mongo:3.6
  web:
    build: "."
    volumes:
      - ".:/code"
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: "mongodb://db:27017/churchsite"
    depends_on:
      - db
