# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8a44b9726f08cbb2e78f5d442bb509f7b2ae39316c2cef166915b6754043ea3546d8f5adf23a57abf04ad1e5ceb7399f8d8dbf6bc9c9dc01073a69f2d72aa3c

test:
  secret_key_base: fde946a95b42107cc51f7ada90e609fc9a43bbd0a2c31f6a5cc2300426942a12692bad605513102fd1f229e869584975c06ad81df60e21919af3caaac95a0be4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
